export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  BOOKSTORE: "/bookstore",
  BOOK_DETAILS: "/bookstore/bookdetails/:id",
  BLOG: "/educational-blog",
  // ARTICLE: '/educational-blog/educational-article',
  ARTICLE: "/educational-article",
  TRAINING_AND_EDUCATION: "/training-and-education",
  JOIN_AS_TRAINER : "/JoinAsTrainer",
  BOOK_YOUR_TRAINER: "/book-your-trainer",
  RECORDED_COURSES: "/recorded-courses",
  // COURSE: '/recorded-courses/recorded-course',
  COURSE: "/recorded-course",
  OPPORTUNITIES_AND_RECOMMENDATIONS: "/opportunities-and-recommendations",
  PARTNER_APPLICATION: "/partner-application",
  TRY_TRADING_FOR_FREE: "/try-trading-for-free",
  VIP_INVESTOR_SERVICES: "/vip-investor-services",
  USER: "/user/:type",
  ADMIN: "/client",
  ADMIN1:"/admin1",
  EMPLOYEE: "/employee",
  NOT_FOUND: "*",
  INVESTORSURVEY:"/investorSurvey",
  //  COURSES RESERVATION: '/RESERVATION/',
  RESERVATION: "/reservation",
  PAYMENT: "/Payment",
  REQUESTCONSULTATION: "/RequestConsultation",
  INLINEBlog: "/inlineBlog/:title",
  COURSECONTENT:"/CourseContent",
  PRIVACYPOLICY:"/privacyPolicy",
  ABOUTUS:"/WhoWeAre",
  CONDITIONS:"/TermsAndCondition",
  ACTIVITIES:"/Activities",
};
