export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  BOOKSTORE: "/bookstore",
  BLOG: "/educational-blog",
  // ARTICLE: '/educational-blog/educational-article',
  ARTICLE: "/educational-article",
  TRAINING_AND_EDUCATION: "/training-and-education",
  RECORDED_COURSES: "/recorded-courses",
  // COURSE: '/recorded-courses/recorded-course',
  COURSE: "/recorded-course",
  OPPORTUNITIES_AND_RECOMMENDATIONS: "/opportunities-and-recommendations",
  PARTNER_APPLICATION: "/partner-application",
  TRY_TRADING_FOR_FREE: "/try-trading-for-free",
  VIP_INVESTOR_SERVICES: "/vip-investor-services",
  USER: "/user/:type",
  ADMIN: "/admin",
  EMPLOYEE: "/employee",
  NOT_FOUND: "*",

  //  COURSES RESERVATION: '/RESERVATION/',

  RESERVATION: "/reservation",
  PAYMENT: "/Payment",
};
